FROM ruby:3.3-alpine
RUN apk add --no-cache build-base postgresql-dev postgresql-client tzdata git yaml-dev libffi-dev gcompat bash
ENV BUNDLE_PATH=/usr/local/bundle \
    GEM_HOME=/usr/local/bundle \
    HOME=/tmp
RUN gem install rails -v '~> 8.0.0' --no-document && chmod -R a+rwX /usr/local/bundle
WORKDIR /app
